# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-06 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dingwei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(0, '高端旗舰'), (1, '中端爆款'), (2, '实用畅销')], default=1, verbose_name='产品定位')),
            ],
            options={
                'verbose_name': '价格定位',
                'verbose_name_plural': '价格定位',
                'db_table': 'good_dingwei',
            },
        ),
        migrations.CreateModel(
            name='GoodBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='品牌名')),
                ('logo', models.CharField(max_length=20, null=True, verbose_name='商标')),
                ('image', models.ImageField(null=True, upload_to='static/brand_img', verbose_name='商标图片')),
            ],
            options={
                'verbose_name': '产品品牌',
                'verbose_name_plural': '产品品牌',
                'db_table': 'good_brand',
            },
        ),
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/goods_img', verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'db_table': 'good_image',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='产品SPU名')),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='产品详情')),
            ],
            options={
                'verbose_name': '商品SPU',
                'verbose_name_plural': '商品SPU',
                'db_table': 'good_spu',
            },
        ),
        migrations.CreateModel(
            name='GoodSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='产品名称')),
                ('desc', models.CharField(max_length=256, verbose_name='产品简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('neicun', models.SmallIntegerField(choices=[(0, '4+32G'), (1, '4+64G'), (2, '6+64G'), (3, '6+128G'), (4, '6+256G'), (5, '8+64G'), (6, '8+128G'), (7, '8+256G'), (8, '64G'), (9, '128G'), (10, '256G'), (11, '512G'), (12, '32G')], default=1, verbose_name='内存')),
                ('image', models.ImageField(default='null', upload_to='static/sku_img', verbose_name='产品图片')),
                ('stock', models.IntegerField(default=1, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='产品状态')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.GoodBrand', verbose_name='产品品牌')),
                ('dingwei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.Dingwei', verbose_name='价格定位')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.Goods', verbose_name='产品SPU')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'good_sku',
            },
        ),
        migrations.CreateModel(
            name='IndexAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='广告词')),
                ('image', models.ImageField(upload_to='static/add_img', verbose_name='广告大图')),
            ],
            options={
                'verbose_name': '广告大图',
                'verbose_name_plural': '广告大图',
                'db_table': 'index_add',
            },
        ),
        migrations.CreateModel(
            name='IndexAdd3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='广告中号标题')),
                ('word', models.CharField(max_length=20, verbose_name='广告小号详情')),
                ('image', models.ImageField(upload_to='static/add_img', verbose_name='广告中号图')),
            ],
            options={
                'verbose_name': '首页三幅广告小图',
                'verbose_name_plural': '首页三幅广告小图',
                'db_table': 'index_add3',
            },
        ),
        migrations.AddField(
            model_name='goodimage',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.GoodSKU', verbose_name='产品'),
        ),
    ]
