# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-06 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='spu_img',
            field=models.ImageField(default='null', upload_to='static/spu_img', verbose_name='产品图片'),
        ),
    ]
